version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: user123456s
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: ./backend/
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/backend/
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend/

volumes:
  db:
